---
- name: Check for directories to store generated variables.
  stat:
    path: host_vars/{{inventory_hostname}}
  register: directory_present

- debug:
    msg: "Directory not present for this host's generated variables.  Directory will be created"
  when: not directory_present.stat.exists

- name: Create directories for generated variables as needed. 
  file:
    path: host_vars/{{inventory_hostname}}
    state: directory
    mode: "u=rw,g=wx,o=rwx"
  when: not directory_present.stat.exists

