underlay:
  ospf:
    routerid: Loopback0
    process: underlay
    area: 0
    cost: 1
  pim:
    interface: Loopback254
    address: 10.200.200.200
    mask: 32
    description: pim_rp_anycast
    grouplist: 233.1.0.0/24
  role: spine
  loopbacks:
    - interface: Loopback0
      ipaddress: 88.88.88.2
      mask: 32
      description: loopback_underlay
  interfaces:
    - interface: Ethernet1/49
      description: to_n9k-leaf-01_ethernet1/34
      ipaddress: 99.99.99.1
      mask: 30
      mtu: 9216
    - interface: Ethernet1/50
      description: to_n9k-leaf-01_ethernet2/30
      ipaddress: 99.99.99.5
      mask: 30
      mtu: 9216
    - interface: Ethernet1/51
      description: to_n9k-leaf-01_ethernet3/49
      ipaddress: 99.99.99.9
      mask: 30
      mtu: 9216
    - interface: Ethernet1/52
      description: to_n9k-leaf-02_ethernet1/34
      ipaddress: 99.99.99.13
      mask: 30
      mtu: 9216
    - interface: Ethernet1/53
      description: to_n9k-leaf-02_ethernet2/30
      ipaddress: 99.99.99.17
      mask: 30
      mtu: 9216
    - interface: Ethernet1/54
      description: to_n9k-leaf-02_ethernet3/49
      ipaddress: 99.99.99.21
      mask: 30
      mtu: 9216
  loopbacks_v2:
   - name: Loopback0
     enabled: true
     description: loopback_underlay
  nve_loopbacks_v2:
   - name: Loopback1
     enabled: true
     description: loopback_underlay
  interfaces_v2:
    - name: Ethernet1/49
      description: to_n9k-leaf-01_ethernet1/34
      enabled: true
      mtu: 9216
      mode: layer3
    - name: Ethernet1/50
      description: to_n9k-leaf-01_ethernet2/30
      enabled: true
      mtu: 9216
      mode: layer3
    - name: Ethernet1/51
      description: to_n9k-leaf-01_ethernet3/49
      enabled: true
      mtu: 9216
      mode: layer3
    - name: Ethernet1/52
      description: to_n9k-leaf-02_ethernet1/34
      enabled: true
      mtu: 9216
      mode: layer3
    - name: Ethernet1/53
      description: to_n9k-leaf-02_ethernet2/30
      enabled: true
      mtu: 9216
      mode: layer3
    - name: Ethernet1/54
      description: to_n9k-leaf-02_ethernet3/49
      enabled: true
      mtu: 9216
      mode: layer3
  loopbacks_l3_v2:
   - name: Loopback0
     ipv4:
       - address: 88.88.88.2/32
         tag: "65100"
  interfaces_l3_v2:
    - name: Ethernet1/49
      ipv4:
        - address: 99.99.99.1/30
    - name: Ethernet1/50
      ipv4:
        - address: 99.99.99.5/30
    - name: Ethernet1/51
      ipv4:
        - address: 99.99.99.9/30
    - name: Ethernet1/52
      ipv4:
        - address: 99.99.99.13/30
    - name: Ethernet1/53
      ipv4:
        - address: 99.99.99.17/30
    - name: Ethernet1/54
      ipv4:
        - address: 99.99.99.21/30
  pim_v2:
    - name: Loopback254
      description: pim_rp_anycast
      enabled: true
  pim_l3_v2:
    - name: Loopback254
      ipv4:
        - address: 10.200.200.200/32
