---
- name: Enable features on Leafs
  hosts: [leaf, bleaf, bgw]
  connection: local
  gather_facts: no
  strategy: free
  
  roles:
    - common
    - leaf
    - bleaf
    - bgw
  
  vars:
    playbook_name: "Enable features on Leaf"

  tasks:
    - name: Create checkpoint
      nxos_rollback:
        checkpoint_file: checkpoint.cfg
        provider: "{{ nxapi }}"
      tags:
        - create_checkpoint
    - block:
        - name: Ensure NETCONF is enabled
          nxos_feature:
            feature: netconf
            state: enabled
          tags:
            - enable_feature_netconf
        - name: Ensure OSPF is enabled
          nxos_feature:
            feature: ospf
            state: enabled
          tags:
            - enable_feature_ospf
        - name: Ensure BGP is enabled
          nxos_feature:
            feature: bgp
            state: enabled
          tags:
            - enable_feature_bgp
        - name: Ensure PIM is enabled
          nxos_feature:
            feature: pim
            state: enabled
          tags:
            - enable_feature_pim
        - name: Ensure interface-vlan is enabled
          nxos_feature:
            feature: interface-vlan
            state: enabled
          tags:
            - enable_feature_interface-vlan
        - name: Ensure scp-server is enabled
          nxos_feature:
            feature: scp-server
            state: enabled
          tags:
            - enable_feature_scp-server
        - name: Ensure LACP is enabled
          nxos_feature:
            feature: lacp
            state: enabled
          tags:
            - enable_feature_lacp
        - name: Ensure vn-segment-vlan-based is enabled
          nxos_feature:
            feature: vn-segment-vlan-based
            state: enabled
          tags:
            - enable_feature_vn-segment-vlan-based
        - name: Ensure nv overlay is enabled
          nxos_feature:
            feature: nv overlay
            state: enabled
          tags:
            - enable_feature_nv_overlay
        - name: Ensure NGOAM  is enabled
          nxos_feature:
            feature: ngoam
            state: enabled
          tags:
            - enable_feature_ngoam
        - name: Configure NGOAM ACL
          nxos_config:
            lines:
              - ngoam install acl 
          tags:
            - configure_ngoam_acl
      rescue:
        - set_fact:
            trigger_msg: True
            send_msg: "{{ playbook_name }} -  error configure on {{ inventory_hostname }}"
          changed_when: True
          notify: notify using spark
        - name: Rollback to checkpoint
          nxos_rollback:
            rollback_to: checkpoint.cfg
...
