---

- name: Configure VPC
  hosts: [leaf]
  connection: local
  gather_facts: no
  roles:
    - common
    #- configure_loopbacks
  vars:
    playbook_name: "Configure vPC"
  tasks:
    - name: Create checkpoint
      nxos_rollback:
        checkpoint_file: checkpoint.cfg
      tags:
        - create_checkpoint
    - block:
      - name: Install feature VPC
        nxos_feature:
          feature: vpc
          state: enabled
        when: vpc.domain is defined
        ignore_errors: True
        tags:
          - install_feature_vpc
          - feature

#########################################################################

      - name: Create the vpc keepalive VRF
        nxos_vrf:
          name: "{{ vpc.vrf }}"
          admin_state: up
          state: present
        when: vpc.domain is defined
        tags:
          - create_vrf_vpc_pl
          - vrf

# Old Way:
      # - name: Configure NVE1 Loopback with secondary IPv4
      #   nxos_config:
      #     lines:
      #       - ip address {{ item["ipaddress_secondary"] }}/{{ item["mask"] }} secondary
      #     parents: interface {{ item["interface"] }}
      #     provider: "{{ nxapi }}"
      #   when: vpc.domain is defined
      #   with_items: "{{ vpc['nve_loopbacks'] }}"
      #   ignore_errors: True
      #   tags:
      #     - configure_nve1_loopback1_secondary
      #     - nve1_loopback1_secondary

# NEW Way:
      # - name: Merge provided configuration with device configuration.
      #   nxos_l3_interfaces:
      #     config:
      #       - name: Ethernet1/6
      #         ipv4:
      #           - address: 192.168.1.1/24
      #             tag: 5
      #           - address: 10.1.1.1/24
      #             secondary: True
      #             tag: 10
      #     state: merged

      # - name: Configure secondary ip on NVE loopback 
      #   nxos_l3_interfaces:
      #     config: "{{ vpc['nve_loopbacks'] }}" 
      #     state: merged
      #   tags:
      #   - vpc
      #   when: vpc.domain is defined

      - name: Configure secondary ip on NVE loopback 
        nxos_l3_interfaces:
          config: "{{ vpc['nve_loopbacks_l3_v2'] }}" 
          state: merged
        tags:
        - vpc
        when: vpc.domain is defined

      #  We can use the with_subelements structure to loop through
      #  nested list data in dictionary primary format.
      # - name: send default interface command to vpc lag members
        #   nxos_config:
        #     lines:
        #       - default interface {{ item.1.member }} 
        #   with_subelements:
        #     - "{{ vpc.vpc_lag_interfaces }}"
        #     - members

#  So is it possible that we may see multiple NVE loopbacks?  We may need to 
#  account for that.  Another option is to put an if statement after secondary ip
#  in the data structure?

#########################################################################

      - name: Configure VPC
        nxos_vpc:
          domain: "{{ vpc.domain }}"
          role_priority: "{{ vpc.priority }}"
          system_priority: "{{ vpc.system_priority }}"
          pkl_vrf: "{{ vpc.vrf }}"
          pkl_dest: "{{ vpc.vpc_dst }}"
          pkl_src: "{{ vpc.vpc_src }}"
          peer_gw: "{{ vpc.peer_gw }}"
          delay_restore: "{{ vpc.delay_restore }}"
          auto_recovery: "{{ vpc.auto_recovery }}"
          state: present
        when: vpc.domain is defined
        ignore_errors: True
        tags:
          - configure_vpc
          - vpc


#########################################################################

      - name: Configure VPC extra parameters
        nxos_config:
          lines:
            - ip arp synchronize
            - ipv6 nd synchronize
            - layer3 peer-router
            - peer-gateway
            - peer-switch
          parents: vpc domain {{ vpc.domain }}
        when: vpc.domain is defined
        ignore_errors: True
        tags:
          - configure_vpc
          - vpc

      - name: Bring up vPC Peer Link Interfaces
        nxos_interfaces:
          config: "{{ vpc['vpc_interfaces'] }}" 
          state: replaced
        when: vpc.domain is defined

      - debug: var=vpc.vpc_lag_interfaces

####################################################################################
#  
#  
####################################################################################

####################################################################################
#  Configure vPC Port Channel Interface
####################################################################################

      - name: Enable vpc port channel interface with nxos_interfaces module
        nxos_interfaces:
          config:
            - name: "port-channel{{ vpc.po_id }}"
              description: 'vPC_peer_link_to_{{ vpc.vpc_peer }}'
              mode: layer2
              enabled: True
          state: merged
        when: vpc.domain is defined


####################################################################################
#  Manually configure port channel in trunk mode
####################################################################################

      - name: Manually configure port channel in trunk mode
        nxos_config:
          lines:
            - interface port-channel {{ vpc.po_id }}
            - switchport mode trunk
        when: vpc.domain is defined

      - name: Configure trunking on portchannel interface with nxos_l2_interfaces module
        nxos_l2_interfaces:
          config:
            - name: "port-channel{{ vpc.po_id }}"
              trunk:
                allowed_vlans: 1-200
          state: merged
        when: vpc.domain is defined

      - name: Configure peer link on VPC Port Channel interface with nxos_vpc_interface module
        nxos_vpc_interface:
          portchannel: "{{ vpc.po_id }}"
          peer_link: yes
          state: present
        when: vpc.domain is defined

###################################################################################
###################################################################################

      - name: Add vpc portchannel interface with nxos_lag_interfaces module
        nxos_lag_interfaces:
          config: "{{ vpc['vpc_lag_interfaces'] }}" 
          state: merged
        when: vpc.domain is defined

      - block:
        - name: validate vpc interfaces member of port channel
          nxos_command:
            commands: 
            - show run interface {{ vpc['vpc_interfaces'][0]['name'] }} 
          register: checksum1
        - debug: var=checksum1
        - assert:
            that:
              - "'active' in checksum1.stdout[0]"
        - name: validate vpc interfaces member of port channel
          nxos_command:
            commands: 
            - show run interface {{ vpc['vpc_interfaces'][1]['name'] }} 
          register: checksum2
        - debug: var=checksum2
        - assert:
            that:
              - "'active' in checksum2.stdout[0]"
        rescue:
##############################################################3
##############################################################3
  # vpc:
  #   vpc_lag_interfaces:
  #     - name: port-channel4096
  #       members:
  #         - member: Ethernet2/1
  #           mode: active
  #         - member: Ethernet2/2
  #           mode: active
##############################################################3
##############################################################3
        - name: send default interface command to vpc lag members
          nxos_config:
            lines:
              - default interface {{ item.1.member }} 
          with_subelements:
            - "{{ vpc.vpc_lag_interfaces }}"
            - members
        - name: delete port channel interface
          nxos_config:
            lines:
            - no interface port-channel {{ vpc.po_id }}
        - name: Bring up vPC Peer Link Interfaces
          nxos_interfaces:
            config: "{{ vpc['vpc_interfaces'] }}" 
            state: replaced
          when: vpc.domain is defined
        - name: Add vpc portchannel interface with nxos_lag_interfaces module
          nxos_lag_interfaces:
            config: "{{ vpc['vpc_lag_interfaces'] }}" 
            state: merged
        - name: Enable vpc port channel interface with nxos_interfaces module
          nxos_interfaces:
            config:
              - name: "port-channel{{ vpc.po_id }}"
                description: 'vPC_peer_link_to_{{ vpc.vpc_peer }}'
                mode: layer2
                enabled: True
            state: merged
        - name: Manually configure port channel in trunk mode
          nxos_config:
            lines:
              - interface port-channel {{ vpc.po_id }}
              - switchport mode trunk
          when: vpc.domain is defined
        - name: Configure trunking on portchannel interface with nxos_l2_interfaces module
          nxos_l2_interfaces:
            config:
              - name: "port-channel{{ vpc.po_id }}"
                trunk:
                  allowed_vlans: 1-200
            state: merged
        - name: Configure peer link on VPC Port Channel interface with nxos_vpc_interface module
          nxos_vpc_interface:
            portchannel: "{{ vpc.po_id }}"
            peer_link: yes
            state: present
        - name: validate port channel configuration present on FIRST port channel member interface
          nxos_command:
            commands: 
            - show run interface {{ vpc['vpc_interfaces'][0]['name'] }} 
          register: checksum1
        - assert:
            that:
              - " 'active' in checksum1.stdout[0]"
            fail_msg: "port channel still has a problem sticking to vpc member interfaces"
            success_msg: "port channel configuration on {{ vpc['vpc_interfaces'][0]['name'] }}"
        - name: validate port channel configuration present on SECOND port channel member interface
          nxos_command:
            commands: 
            - show run interface {{ vpc['vpc_interfaces'][1]['name'] }} 
          register: checksum2
        - assert:
            that:
              - " 'active' in checksum2.stdout[0]"
            fail_msg: "port channel still has a problem sticking to vpc member interfaces"
            success_msg: "port channel configuration on {{ vpc['vpc_interfaces'][0]['name'] }}"
        when: vpc.domain is defined

      - name: Configure KAL Link between vPC Members
        nxos_interfaces:
          config:  "{{ vpc.kal_interface }}"
          state: merged
        when: vpc.domain is defined

      - name: Ensure keepalive vrf exists keepalive interface
        nxos_vrf_interface:
          vrf: "{{ vpc.vrf }}"
          interface: "{{ vpc.kal_interface_l3[0]['name'] }}"
          state: present
        when: vpc.domain is defined

      - name: Configure Layer3 interface addressing (test scenario)
        nxos_l3_interfaces:
          config: "{{ vpc.kal_interface_l3 }}"
          state: merged
        when: vpc.domain is defined



###########################################################################
#   This is about kpl vlan which we're not using
#   This is about kpl vlan which we're not using
#   This is about kpl vlan which we're not using
###########################################################################
      # - name: Create L2 VLAN VPC Underlay
      #   nxos_vlan:
      #     vlan_id: "{{ vpc.vlan }}"
      #     admin_state: up
      #     name: vpc_undelay
      #     provider: "{{ nxapi }}"
      #   when: vpc.domain is defined
      #   ignore_errors: True
      #   tags:
      #     - configure_l2_vpc_underlay_vlan
      #     - vpc_underlay_vlan

      # - name: Merge provided configuration with device configuration.
      #   nxos_vlans:
      #     config:
      #       - vlan_id: 5
      #         name: test-vlan5
      #       - vlan_id: 10
      #         enabled: False
      #     state: merged


###########################################################################
#   Need to pull the kal interface info from vpc variables and configure
#   the link here.
# What looks to be happening here is that the original programmer is 
# using the kal synatax to add a L3 link between the vpc peers.  
# Confirm.
###########################################################################

#This is a test addition to this file. 



#       - name: Create L3 VLAN VPC PL
#         nxos_interface:
#           name: "Vlan{{ vpc.vlan }}"
#           admin_state: up
#           state: present
#           provider: "{{ nxapi }}"
#         when: vpc.domain is defined
#         ignore_errors: True
#         tags:
#           - configure_l3_vpc_underlay_vlan
#           - vpc_underlay_vlan

#       - name: Configure L3 VLAN VPC Underlay IPv4
#         nxos_ip_interface:
#           interface: "Vlan{{ vpc.vlan }}"
#           version: v4
#           addr: "{{ vpc.vlan_underlay_ipv4 }}"
#           mask: "{{ vpc.vlan_underlay_mask }}"
#           state: present
#           provider: "{{ nxapi }}"
#         when: vpc.domain is defined
#         ignore_errors: True
#         tags:
#           - configure_l3_vpc_underlay_vlan
#           - vpc_underlay_vlan

#       - name: Configure L3 VLAN VPC Underlay PIM
#         nxos_pim_interface:
#           interface: "Vlan{{ vpc.vlan }}"
#           sparse: true
#           state: present
#           provider: "{{ nxapi }}"
#         when: vpc.domain is defined
#         ignore_errors: True
#         tags:
#           - configure_pim_vpc_underlay_vlan
#           - vpc_underlay_vlan

#       - name: Confgure OSPF VLAN VPC Underlay
#         nxos_interface_ospf:
#           interface: "Vlan{{ vpc.vlan }}"
#           ospf: "{{ underlay['ospf']['process'] }}"
#           area: "{{ underlay['ospf']['area'] }}"
#           cost: default
#           passive_interface: false
#           state: present
#           provider: "{{ nxapi }}"
#         when: vpc.domain is defined
#         ignore_errors: True
#         tags:
#           - configure_ospf_vpc_underlay_vlan
#           - vpc_underlay_vlan

#       - name: Confgure OSPF VLAN Underlay network type
#         nxos_config:
#           lines:
#             - ip ospf network point-to-point
#           parents: "interface Vlan{{ vpc.vlan }}"
#           provider: "{{ nxapi }}"
#         when: vpc.domain is defined
#         ignore_errors: True
#         tags:
#           - configure_ospf_vpc_underlay_vlan
#           - vpc_underlay_vlan
#       rescue:
#         - set_fact:
#             trigger_msg: True
#             send_msg: "{{ playbook_name }} -  error configure on {{ inventory_hostname }}"
#           changed_when: True
#           notify: notify using spark
#         - name: Rollback to checkpoint
#           nxos_rollback:
#             rollback_to: checkpoint.cfg
#             provider: "{{ nxapi }}"
# ...

   
#     - name: show feature
#       nxos_command:
#         commands:
#           - show vpc
#       register: vpc
#     - name: show feature
#       debug: msg="{{vpc.stdout[0]}}"





...


