---
- name: json-pretty-testing
  #hosts: [leaf,bleaf,bgw,spine]
  hosts: [leaf,spine]
  #connection: local
  gather_facts: no
  roles:
    - common
    #- configure_loopbacks
  vars:
    playbook_name: "json-pretty-testing"

  tasks:
    - name: GATHER LIST OF INTERFACES
      nxos_command:
        commands:
          - show cdp neighbors | json-pretty
      register: list

    #- name: DETERMINE AMOUNT OF CDP NEIGHBORS
    #  nxos_command:
    #    commands:
    #      - show cdp neighbors | i Eth|mgmt | count
    #  register: count

    #- set_fact:
    #    AMOUNT="{{ count.stdout_lines[0] | int }}"

    #- debug:
    #    msg="{{AMOUNT}}"

    #- debug: msg="{{ list.stdout[0].TABLE_cdp_neighbor_brief_info.ROW_cdp_neighbor_brief_info[0].intf_id }}"
    #  with_items: "{{ list }}"

    - debug:
        var: item
      loop: "{{ list.stdout[0] | json_query('TABLE_cdp_neighbor_brief_info.ROW_cdp_neighbor_brief_info[*].intf_id') }}"
      register: local

    #- set_fact:
    #    local1="{{local.results[0].item[0:]}}"
    #    local2="{{local.results[1].item[0:]}}"
    #    local3="{{local.results[2].item[0:]}}"
    #    local4="{{local.results[3].item[0:]}}"
    #    local5="{{local.results[4].item[0:]}}"
    #    local6="{{local.results[5].item[0:]}}"
    #  ignore_errors: yes


    #- debug:
    #    msg="{{local1}}"
    #    msg="{{local2}}"
    #    msg="{{local3}}"
    #    msg="{{local4}}"
    #    msg="{{local5}}"
    #    msg="{{local6}}"
    #  ignore_errors: yes

    #- set_fact: {"{{ local_int_1 }}":"{{ local.results[0].item[0:] }}"}

    - debug:
        var: item
      loop: "{{ list.stdout[0] | json_query('TABLE_cdp_neighbor_brief_info.ROW_cdp_neighbor_brief_info[*].device_id') }}"

    - debug:
        var: item
      loop: "{{ list.stdout[0] | json_query('TABLE_cdp_neighbor_brief_info.ROW_cdp_neighbor_brief_info[*].port_id') }}"