---
- name: json-pretty-testing
  #hosts: [leaf,bleaf,bgw,spine]
  hosts: [leaf,spine]
  #connection: local
  gather_facts: no
  roles:
    - common
    #- configure_loopbacks
  vars:
    playbook_name: "json-pretty-testing"

  tasks:
    - name: GATHER LIST OF CDP LOCAL INTERFACES
      nxos_command:
        commands:
          - show cdp neighbors | json-pretty
      register: cdp
      tags: gather, looptest

    - name: GATHER LIST OF CDP LOCAL INTERFACES
      debug: var=cdp

    - name: access nested data in json-pretty format
      debug: msg="{{ cdp.stdout[0].TABLE_cdp_neighbor_brief_info.ROW_cdp_neighbor_brief_info[0].intf_id }}"
      with_items: "{{ cdp }}"
      tags: gather

    - name: print a list of intf_id's from stdout
      debug: msg="{{ cdp.stdout|map(attribute='{{intf_id}}')|list }}"
      tags: looptest

    - name:  This apparently builds a list to be used in the next stanza
      debug: msg="{{ item.stdout[0].TABLE_cdp_neighbor_brief_info.ROW_cdp_neighbor_brief_info[0].intf_id }}"
      with_items: "{{ cdp }}"
      register: loop
      tags: looptest

    - name: GATHER DISTANT DEVICE PORT
      nxos_command:
        commands:
          - command: show cdp neigh int "{{ item }}"
            output: json
        with_items: "{{ loop }}"
      register: afterloop
      tags: looptest

    - debug: var=afterloop
      tags: looptest

    #- name: GATHER DISTANT DEVICE PORT
    #  nxos_command:
    #    commands:
    #      - command: show cdp neigh int mgmt0 | json-pretty
    #  register: distant_int
    #  tags: test

    - debug: msg="{{ distant_int.stdout[0].TABLE_cdp_neighbor_brief_info.ROW_cdp_neighbor_brief_info.port_id }}"
      tags: test

    - debug: msg="{{ distant_int.stdout[0].TABLE_cdp_neighbor_brief_info.ROW_cdp_neighbor_brief_info.device_id }}"
      tags: test