---
- name: Enable and configure telemetry
  hosts: all
  connection: local
  gather_facts: no
  #strategy: free
#  vars:
#    csvfile: "{{ lookup('file', 'Scott_EVPN_Config_Template.csv')}}"
    
  tasks:
  - name: Import host-specific facts from a XLS file
    xls_to_facts:
#      src: "evpn_config_template.xlsx" 
      src: "Scott_EVPN_Config_Template.xlsx" 

  # - debug:
  #     var='spreadsheet_Scott'

  - block:
    - name: Generate Hostnames
      template: >
        src=test_csv.j2
        dest=test_csv_output.yml
    run_once: true

