---
- block: 
  - name: Check to see if legacy files exist and delete if necessary.
    stat:
      path: group_vars/all/generated_vtep_anycast_subnets.yml
    register: file_present

  - file: path=group_vars/all/generated_vtep_anycast_subnets.yml state=absent
    when: file_present.stat.exists

  - name: Generate VTEP Anycast Subnets
    template: >
      src=main.j2
      dest=group_vars/all/generated_vtep_anycast_subnets.yml
  run_once: true
