bgw:
  siteid: 1000
  asn: 65100
  vip:
    ip: 172.16.1.100
    mask: 32
    description: Multi-Site VIP Loopback
    interface: loopback100

  bgp:
    - neighbor: 10.20.10.3
      asn: 65200
      multihop: 5
      updatesource: Loopback0
    - neighbor: 10.20.10.4
      asn: 65200
      multihop: 5
      updatesource: Loopback0



  fabric_interfaces:
    - local_interface: Eth1/49
      remote_interface: Ethernet2/10
      remote_ne: n9k-spine-1


  dci_interfaces:
    - local_interface: Eth1/20
      remote_interface: Ethernet1/2
      remote_ne: wan
      local_ip: 172.16.1.2
      remote_ip: 172.16.1.1
      mtu: 9216
      mask: 30
      asn: 65000



