underlay:
  ospf:
    routerid: Loopback0
    process: underlay
    area: 0
    cost: 1
  pim:
    interface: Loopback254
    address: 10.154.154.154
    mask: 32
    description: pim_rp_anycast
    grouplist: 233.1.0.0/24
  role: leaf
  loopbacks:
    - interface: Loopback0
      ipaddress: 10.10.10.1
      mask: 32
      description: loopback_underlay
  nve_loopbacks:
    - interface: Loopback1
      ipaddress: 10.100.100.1
      mask: 32
      description: loopback_underlay
  interfaces:
    - interface: Eth1/49
      description: to_n9k-spine-1_ethernet2/1
      ipaddress: 10.1.1.18
      mask: 30
      mtu: 9216
