underlay:
  ospf:
    routerid: Loopback0
    process: underlay
    area: 0
    cost: 1
  pim:
    interface: Loopback254
    address: 10.200.200.200
    mask: 32
    description: pim_rp_anycast
    grouplist: 233.1.0.0/24
  role: leaf
  loopbacks:
    - interface: Loopback0
      ipaddress: 88.88.88.1
      mask: 32
      description: loopback_underlay
  nve_loopbacks:
    - interface: Loopback1
      ipaddress: 20.20.20.1
      mask: 32
      description: loopback_underlay
  interfaces:
    - interface: Ethernet1/34
      description: to_n9k-spine-01_ethernet1/52
      ipaddress: 99.99.99.14
      mask: 30
      mtu: 9216
    - interface: Ethernet2/30
      description: to_n9k-spine-01_ethernet1/53
      ipaddress: 99.99.99.18
      mask: 30
      mtu: 9216
    - interface: Ethernet3/49
      description: to_n9k-spine-01_ethernet1/54
      ipaddress: 99.99.99.22
      mask: 30
      mtu: 9216
  loopbacks_v2:
   - name: Loopback0
     enabled: true
     description: loopback_underlay
  nve_loopbacks_v2:
   - name: Loopback1
     enabled: true
     description: loopback_underlay
  interfaces_v2:
    - name: Ethernet1/34
      description: to_n9k-spine-01_ethernet1/52
      enabled: true
      mtu: 9216
      mode: layer3
    - name: Ethernet2/30
      description: to_n9k-spine-01_ethernet1/53
      enabled: true
      mtu: 9216
      mode: layer3
    - name: Ethernet3/49
      description: to_n9k-spine-01_ethernet1/54
      enabled: true
      mtu: 9216
      mode: layer3
  loopbacks_l3_v2:
   - name: Loopback0
     ipv4:
       - address: 88.88.88.1/32
         tag: "65100"
  nve_loopbacks_l3_v2:
    - name: Loopback1
      ipv4:
        - address: 20.20.20.1/32
          tag: "65100"
  interfaces_l3_v2:
    - name: Ethernet1/34
      ipv4:
        - address: 99.99.99.14/30
    - name: Ethernet2/30
      ipv4:
        - address: 99.99.99.18/30
    - name: Ethernet3/49
      ipv4:
        - address: 99.99.99.22/30
  pim_v2:
    - name: Loopback254
      description: pim_rp_anycast
      enabled: true
  pim_l3_v2:
    - name: Loopback254
      ipv4:
        - address: 10.200.200.200/32
