---
- block: 
  - name: Check to see if legacy files exist and delete if necessary.
    stat:
      path: host_vars/{{inventory_hostname}}/generated_vpc_variables.yml
    register: file_present

  - file: path=host_vars/{{inventory_hostname}}/generated_vpc_variables.yml state=absent
    when: file_present.stat.exists

  - name: Validate vPC Peer Dict Exists
    debug: msg={{ vpc_pairs }}

  - name: Generate VPC variables
    template: >
      src=main.j2
      dest=host_vars/{{inventory_hostname}}/generated_vpc_variables.yml
  #run_once: true
