---
- name: Check to see if legacy files exist and delete if necessary.
  stat:
    path: host_vars/{{inventory_hostname}}/generated_underlay_variables.yml
  register: file_present

- file: path=host_vars/{{inventory_hostname}}/generated_underlay_variables.yml state=absent
  when: file_present.stat.exists

- name: Generate Underlay variables
  template: >
    src=main.j2
    dest=host_vars/{{inventory_hostname}}/generated_underlay_variables.yml
